
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="../js/app.js" ></script>
    <script src=".../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"> </script>
    <link href="css/layout.css" rel="stylesheet" />
    <link href="css/index.css" rel="stylesheet" />
    <link href="main.scss"/>
</head>
