
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script type="module" src="js/app.js" ></script>
    <script type="module" src="bootstrap-5.2.3/js/bootstrap.bundle.min.js"> </script>
    <link href="bootstrap-5.2.3/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/layout.css" rel="stylesheet" />
    <link href="css/index.css" rel="stylesheet" />
    <link href="css/changePassword.css" rel="stylesheet" />

</head>
